### ISSUE TITLE
需要将 Pods 文件夹 ignore

### ISSUE THREAD

**Issue by SeanChense** [wongkoo/Jobs#1]
在 `.gitignore` 中添加  `Pods/` 忽略该文件夹。

**Comment by jkyin** [comment]
@SeanChense 这个按需求来，只有建议没有标准。作者的意思应该是为了方便大家快速编译运行学习。

**Comment by SeanChense** [comment]
@jkyin 我以为这个是标准做法来着

**Comment by wongkoo** [comment]
需要在源代码控制中忽略Pods目录么?
是否源代码控制Pods目录取决于你，各种工程的工作流是不同的，我们推荐在.gitignore文件中增加Pods目录。然而，最后的决定还是由你自己做，下面是各自的优劣.
优点
在源码控制中，更小的库管理;
CocoaPods能够根据各种库的源代码重新创建一样的安装;
不需要处理依赖库各种源代码的冲突;
缺点
Pods 的库源可能关掉了.
依赖的库源码不会同样的创建.
需要internet连接，并且要安装CocoaPods.

之前没注意这个问题，一起学习～～

**Comment by jkyin** [comment]
@wongkoo 如果没有其他问题，那么这个 issue 可以 close 了。
